name = "beatroot"
main = "src/index.js"
compatibility_date = "2023-02-05"
route = "https://api.slin.dev/beatroot/v1/*"

kv_namespaces = [
  { binding = "BEATROOT", "id" = "b74d4458fac9410e8e3e503a5c7d6ca2" },
]
